//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int auction_id { get; set; }
        public Nullable<int> lot_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> bid1 { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Lot Lot { get; set; }
    }
}
