//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employee_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string number { get; set; }
        public Nullable<int> post_id { get; set; }
        public Nullable<int> auth_id { get; set; }
    
        public virtual Auth Auth { get; set; }
        public virtual Post Post { get; set; }
    }
}
