//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lot()
        {
            this.Bid = new HashSet<Bid>();
            this.Sale = new HashSet<Sale>();
        }
    
        public int lot_id { get; set; }
        public string name { get; set; }
        public Nullable<int> seller_id { get; set; }
        public Nullable<int> min_price { get; set; }
        public Nullable<int> preferred_price { get; set; }
        public Nullable<System.DateTime> start_day { get; set; }
        public Nullable<System.DateTime> planned_close_day { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bid { get; set; }
        public virtual LotLocation LotLocation { get; set; }
        public virtual LotType LotType { get; set; }
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
